- name: Install Nginx
  ansible.builtin.command:
    cmd: amazon_linux_extras install nginx1 -y

- name: Start and enable Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Copy the index.html to web root
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    owner: nginx
    group: nginx
    mode: '0644'

