---
- hosts: localhost
  become: true
  gather_facts: true

  vars:
    # ansible_connection: aws_ssm
    # ansible_aws_ssm_region: us-east-1
    # ansible_aws_ssm_bucket_name: copy-static-website
    ansible_aws_ssm_timeout: 3000

  tasks:
    - name: Update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install Nginx from Amazon Linux Extras
      ansible.builtin.command:
        cmd: amazon-linux-extras install nginx1 -y

    - name: Install nginx
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop: 
        - python
        - awscli
        - nodejs
        - npm 
    
    - name: Change Nginx Configuration file   
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: "{{ nginx_path }}"

    - name: Ensure Python3 pip is installed
      ansible.builtin.yum:
        name: python3-pip
        state: present

    - name: Install botocore and boto3 
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:  
        - botocore
        - boto3   
            
    - name: Make folder in EC2 instance
      ansible.builtin.file:
          path: /home/react-app
          state: directory
          mode: '0755'
        
    - name: Copy React-app folder from git
      ansible.builtin.git: 
        repo: "https://github.com/sujatadhl/pipeline-github.git/react-app"
        dest: "/home/react-app"
        version: "git-actions"

    - name: Install PM2 globally
      ansible.builtin.npm:
        name: pm2
        global: yes

    - name: Install dependencies
      ansible.builtin.npm:
        path: /home/react-app

    - name: Start the react app 
      ansible.builtin.command: pm2 start --name react-app npm -- start
      args:
        chdir: /home/react-app
      notify: Restart Nginx 

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted