---
- hosts: all
  become: true
  gather_facts: true

  vars:
    # ansible_connection: aws_ssm
    # ansible_aws_ssm_region: us-east-1
    # ansible_aws_ssm_bucket_name: copy-static-website
    ansible_aws_ssm_timeout: 3000

    tasks:
    - name: Install EPEL repository
      amazon.aws.amazon_linux_extras:
        name: epel
        state: present
        
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Copy the index.html to web root
      copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

