name: Upload to S3
on:
    push:
      branches:
        - github-actions
    pull_request:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
    AWS_DEFAULT_REGION: us-east-1

jobs:
    create-resources:
      runs-on: ubuntu-latest
        
      steps:
        - name: Checkout 
          uses: actions/checkout@v3
            
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v1
          
        - name: Terraform init
          run: |
            cd terraform
            terraform init
        
        - name: Terraform plan
          run: |
            cd terraform
            terraform plan  -var-file="var.tfvars"   

        - name: Terraform apply 
          run: |
            cd terraform
            terraform apply -var-file="var.tfvars" -auto-approve      

        - name: Run user data
          run: |
            cd terraform
            sudo apt install awscli
            aws ec2 run-instances --image-id ami-0d191299f2822b1fa --count 1 --instance-type t2.micro --user-data file://terraform/user-data.sh

  
        
              

           