name: Upload to S3
on:
    push:
      branches:
        - github-actions
    pull_request:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
    AWS_DEFAULT_REGION: us-east-1

jobs:
    create-resources:
      runs-on: ubuntu-latest
        
      steps:
        - name: Checkout 
          uses: actions/checkout@v3
            
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v1
          
        - name: Terraform init
          run: |
            cd terraform
            terraform init
        
        - name: Terraform plan
          run: |
            cd terraform
            terraform plan   

        - name: Terraform apply 
          run: |
            cd terraform
            terraform apply -var-file="var.tfvars" -auto-appro         
    

  
        
              

           