name: Upload to S3
on:
    push:
      branches:
        - github-actions
    pull_request:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
    AWS_DEFAULT_REGION: us-east-1

jobs:
    upload-to-s3:
      runs-on: ubuntu-latest
        
      steps:
        - name: Checkout code 
          uses: actions/checkout@v3

        - name: Install AWS CLI
          run: |
            sudo apt-get update
            sudo apt install -y awscli  
    
        - name: Ensure S3 bucket is created
          run: |
            BUCKET_NAME="sujata-linux2"
            if aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
              aws s3 rb s3://$BUCKET_NAME --force
            fi
            aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1    
         
        - name: Add ansible file to s3
          run: aws cp ansible/. s3://sujata-linux2  

    create-resources:
      runs-on: ubuntu-latest
        
      steps:
        - name: Checkout 
          uses: actions/checkout@v3
            
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v1
          
        - name: Terraform init
          run: |
            cd terraform
            terraform init
        
        - name: Terraform plan
          run: |
            cd terraform
            terraform plan  -var-file="var.tfvars"   

        - name: Terraform apply 
          run: |
            cd terraform
            terraform apply -var-file="var.tfvars" -auto-approve      

        - name: Run user data
          run: |
            cd terraform
            aws ec2 run-instances --image-id ami-0d191299f2822b1fa --count 1 --instance-type t2.micro --subnet-id subnet-0f97b0bb45cdeb3b7 --user-data $(base64 userdata.sh  --wrap=0)

      
                

           
